import { signIn, signOut, useSession } from "next-auth/react";
import { AIChatBubble, UserChatBubble } from "~/components/chat-bubbles";
import { TextareaWithButton } from "~/components/textarea-with-button";
import { Button } from "~/components/ui/button";
import { ModeToggle } from "~/components/ui/mode-toggle";
import Head from "next/head";

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>AI Travel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex max-h-screen min-h-screen w-full flex-col overflow-x-hidden overflow-y-hidden">
        <nav className="">
          <div className="flex flex-row items-center justify-center gap-4 p-4">
            <div className="grow">
              <h1 className="text-5xl font-extrabold tracking-tight">
                <span className="text-[hsl(280,100%,70%)]">AI</span> Travel
              </h1>
            </div>
            <p className="leading-7">
              {sessionData && (
                <span>Logged in as {sessionData.user?.name}</span>
              )}
            </p>
            <Button
              size={"sm"}
              onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
              {sessionData ? "Sign out" : "Sign in"}
            </Button>
            <ModeToggle />
          </div>
        </nav>
        <div className="grow gap-10 overflow-y-auto px-96">
          <AIChatBubble
            text="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse magni
            odio reiciendis quis, laudantium molestiae in libero soluta unde
            commodi maiores corrupti dolorem, eius, mollitia cupiditate corporis
            alias quo? Veritatis."
          />
          <UserChatBubble text="I'm ok what about you?" />
        </div>
        <div className="">
          <p className="container p-8">
            <TextareaWithButton />
          </p>
        </div>
      </main>
    </>
  );
}
