import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Button } from "~/components/ui/button";
import { ModeToggle } from "~/components/ui/mode-toggle";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "~/components/ui/navigation-menu";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>AI Travel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen antialiased">
        <div className="flex h-full w-full flex-row overflow-x-hidden">
          <div className="flex h-full flex-auto flex-col p-6">
            <div className="container flex flex-row gap-12">
              <h1 className="grow text-4xl font-extrabold">
                <span className="text-[hsl(280,100%,70%)]">AI</span> Travel
              </h1>
              <ModeToggle />
            </div>
            <div className="flex h-full flex-auto flex-shrink-0 flex-col rounded-2xl  p-4">
              <div className="mb-4 flex h-full flex-col overflow-x-auto">
                <div className="flex h-full flex-col">
                  <div className="grid grid-cols-12 gap-y-2">
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>Hey How are you today?</div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>
                            Lorem ipsum dolor sit amet, consectetur adipisicing
                            elit. Vel ipsa commodi illum saepe numquam maxime
                            asperiores voluptate sit, minima perspiciatis.
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>Hey How are you today?</div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>
                            Lorem ipsum dolor sit amet, consectetur adipisicing
                            elit. Vel ipsa commodi illum saepe numquam maxime
                            asperiores voluptate sit, minima perspiciatis.
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-6 col-end-13 rounded-lg p-3">
                      <div className="flex flex-row-reverse items-center justify-start">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative mr-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>I'm ok what about you?</div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-6 col-end-13 rounded-lg p-3">
                      <div className="flex flex-row-reverse items-center justify-start">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative mr-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>
                            Lorem ipsum dolor sit, amet consectetur adipisicing.
                            ?
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>Lorem ipsum dolor sit amet !</div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-6 col-end-13 rounded-lg p-3">
                      <div className="flex flex-row-reverse items-center justify-start">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative mr-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>
                            Lorem ipsum dolor sit, amet consectetur adipisicing.
                            ?
                          </div>
                          <div className="absolute bottom-0 right-0 -mb-5 mr-2 text-xs text-gray-500">
                            Seen
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div>
                            Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Perspiciatis, in.
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-start-1 col-end-8 rounded-lg p-3">
                      <div className="flex flex-row items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-indigo-500">
                          A
                        </div>
                        <div className="relative ml-3 rounded-xl px-4 py-2 text-sm shadow">
                          <div className="flex flex-row items-center">
                            <button className="flex h-8 w-10 items-center justify-center rounded-full bg-indigo-600 hover:bg-indigo-800">
                              <svg
                                className="h-6 w-6 "
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                                xmlns="http://www.w3.org/2000/svg"
                              >
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth="1.5"
                                  d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
                                ></path>
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth="1.5"
                                  d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                                ></path>
                              </svg>
                            </button>
                            <div className="ml-4 flex flex-row items-center space-x-px">
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-4 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-10 w-1 rounded-lg "></div>
                              <div className="h-10 w-1 rounded-lg "></div>
                              <div className="h-12 w-1 rounded-lg "></div>
                              <div className="h-10 w-1 rounded-lg "></div>
                              <div className="h-6 w-1 rounded-lg "></div>
                              <div className="h-5 w-1 rounded-lg "></div>
                              <div className="h-4 w-1 rounded-lg "></div>
                              <div className="h-3 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-10 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-10 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-1 w-1 rounded-lg "></div>
                              <div className="h-1 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-8 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-2 w-1 rounded-lg "></div>
                              <div className="h-4 w-1 rounded-lg "></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex h-16 w-full flex-row items-center rounded-xl px-4">
                <div className="ml-4 flex-grow">
                  <div className="relative w-full">
                    <input
                      type="text"
                      className="flex h-10 w-full rounded-xl border pl-4 focus:border-indigo-300 focus:outline-none"
                    />
                    <button className="absolute right-0 top-0 flex h-full w-12 items-center justify-center text-gray-400 hover:text-gray-600">
                      <svg
                        className="h-6 w-6"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                        ></path>
                      </svg>
                    </button>
                  </div>
                </div>
                <div className="ml-4">
                  <button className="flex flex-shrink-0 items-center justify-center rounded-xl bg-indigo-500 px-4 py-1  hover:bg-indigo-600">
                    <span>Send</span>
                    <span className="ml-2">
                      <svg
                        className="-mt-px h-4 w-4 rotate-45 transform"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
                        ></path>
                      </svg>
                    </span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container flex flex-col gap-12 p-4">
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </div>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
}
